# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for prometheus-openstack-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  tags:
    prometheus_openstack_exporter: quay.io/attcomdev/prometheus-openstack-exporter:3231f14419f0c47547ce2551b7d884cd222104e6
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    image_repo_sync: docker.io/docker:17.07.0
    ks_user: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
  pull_policy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

labels:
  openstack_exporter:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

pod:
  affinity:
    anti:
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: kubernetes.io/hostname
  mounts:
    prometheus_openstack_exporter:
      prometheus_openstack_exporter:
      init_container: null
  replicas:
    prometheus_openstack_exporter: 1
  lifecycle:
    upgrades:
      revision_history: 3
      pod_replacement_strategy: RollingUpdate
      rolling_update:
        max_unavailable: 1
        max_surge: 3
    termination_grace_period:
      prometheus_openstack_exporter:
        timeout: 30
  resources:
    enabled: false
    kube_state_metrics:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    jobs:
      image_repo_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_user:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - prometheus-openstack-exporter-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry
    ks_user:
      services:
        - endpoint: internal
          service: identity
    prometheus_openstack_exporter:
      jobs:
        - prometheus-openstack-exporter-ks-user
      services:
        - endpoint: internal
          service: identity

conf:
  prometheus_openstack_exporter:
    OS_POLLING_INTERVAL: 30
    TIMEOUT_SECONDS: 20
    OS_RETRIES: 1

secrets:
  identity:
    admin: prometheus-openstack-exporter-keystone-admin
    user: prometheus-openstack-exporter-keystone-user

endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000
  prometheus_openstack_exporter:
    namespace: null
    hosts:
      default: openstack-metrics
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: 'http'
    port:
      exporter:
        default: 9103
  identity:
    name: keystone
    auth:
      admin:
        region_name: RegionOne
        username: admin
        password: password
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      user:
        role: admin
        region_name: RegionOne
        username: prometheus-openstack-exporter
        password: password
        project_name: service
        user_domain_name: default
        project_domain_name: default
    hosts:
      default: keystone-api
      public: keystone
    host_fqdn_override:
      default: null
    path:
      default: /v3
    scheme:
      default: 'http'
    port:
      admin:
        default: 35357
      api:
        default: 80

monitoring:
  prometheus:
    enabled: true
    openstack_exporter:
      scrape: true

network:
  openstack_metrics_exporter:
    port: 9103

manifests:
  configmap_bin: true
  deployment: true
  job_image_repo_sync: true
  job_ks_user: true
  secret_keystone: true
  service: true
