- name: "installing python {{ package }}"
  become: true
  become_user: root
  environment:
    http_proxy: "{{ proxy.http }}"
    https_proxy: "{{ proxy.https }}"
    no_proxy: "{{ proxy.noproxy }}"
  pip:
    name: "{{ package }}"
