dependencies:
  static:
    grafana:
      jobs: null
      services: null
manifests:
  ingress: false
  job_db_init: false
  job_db_init_session: false
  job_db_session_sync: false
  secret_db: false
  secret_db_session: false
  service_ingress: false
conf:
  grafana:
    database:
      type: sqlite3
    session:
      provider: file
      provider_config: sessions
network:
  grafana:
    ingress:
      public: false
    node_port:
      enabled: true
