# Copyright 2017 The Openstack-Helm Authors.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

- name: setting up bootstrap tiller
  block:
    - name: pull the helm tiller Image
      become: true
      become_user: root
      docker_image:
        pull: true
        name: "{{ helm.tiller_image }}"
    - name: deploying bootstrap tiller
      become: true
      become_user: root
      docker_container:
        name: "helm-tiller"
        image: "{{ helm.tiller_image }}"
        state: started
        detach: true
        recreate: yes
        network_mode: host
        volumes:
          - /etc/kubernetes/admin.conf:/etc/kubernetes/admin.conf:ro
        env:
          KUBECONFIG=/etc/kubernetes/admin.conf
      register: kubeadm_aio_tiller_container
      ignore_errors: True
    - name: wait for tiller to be ready
      delegate_to: 127.0.0.1
      command: helm version --server
      environment:
        HELM_HOST: 'localhost:44134'
      register: task_result
      until: task_result.rc == 0
      retries: 120
      delay: 5

- name: kubeadm | get certs
  block:
    - name: kubeadm | get kubeapi cert
      shell: cat /etc/kubernetes/pki/apiserver.crt | base64 -w0
      register: kubeadm_kubeapi_cert
    - name: kubeadm | get kubeapi key
      shell: cat /etc/kubernetes/pki/apiserver.key | base64 -w0
      register: kubeadm_kubeapi_key

- name: kubeadm | keystone auth
  delegate_to: 127.0.0.1
  block:
    - name: kubeadm | keystone auth
      command: "helm upgrade --install kubernetes-keystone-webhook /opt/charts/kubernetes-keystone-webhook --namespace=kube-system --set endpoints.identity.namespace=openstack --set endpoints.kubernetes.auth.api.tls.crt={{ kubeadm_kubeapi_cert.stdout }} --set endpoints.kubernetes.auth.api.tls.key={{ kubeadm_kubeapi_key.stdout }}"
      environment:
        HELM_HOST: 'localhost:44134'
    - name: kubeadm | keystone auth
      command: helm status kubernetes-keystone-webhook
      environment:
        HELM_HOST: 'localhost:44134'
      register: kubeadm_helm_keystone_status
    - name: kubeadm | keystone auth
      debug:
        msg: "{{ kubeadm_helm_keystone_status }}"

- name: kubeadm | setup api server for keystone
  block:
    - name: kubeadm | copying webhook config to host
      become: true
      become_user: root
      template:
        src: webhook.kubeconfig.j2
        dest: /etc/kubernetes/pki/webhook.kubeconfig
        mode: 0640
    - name: kubeadm | configuring api server
      become: true
      become_user: root
      shell: |
        # TODO(lamt): Clean up this way of restarting the kube-apiserver. Preferably,
        # the setting is in place when the kube-apiserver comes up. Currently, the
        # kube-apiserver does not start whenever the webhook fails.
        cat /etc/kubernetes/manifests/kube-apiserver.yaml > /tmp/kube-apiserver.yaml
        sed -i '/etcd-keyfile/a \ \ \ \ -\ --authentication-token-webhook-config-file=/etc/kubernetes/pki/webhook.kubeconfig\n \ \ \ \- --authorization-webhook-config-file=/etc/kubernetes/pki/webhook.kubeconfig' /tmp/kube-apiserver.yaml
        sed -i -e 's/Node,RBAC/Node,Webhook,RBAC/g' /tmp/kube-apiserver.yaml
        sed -i '/hostNetwork: true/a\ \ dnsPolicy: ClusterFirstWithHostNet' /tmp/kube-apiserver.yaml
        mv /tmp/kube-apiserver.yaml /etc/kubernetes/manifests/kube-apiserver.yaml

- name: "removing bootstrap tiller container"
  become: true
  become_user: root
  docker_container:
    name: "helm-tiller"
    state: absent
