# Copyright 2017 The Openstack-Helm Authors.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

- block:
    - name: base kubeadm deploy
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/kubernetes/
        - /etc/systemd/system/kubelet.service.d/
        - /var/lib/kubelet/
    - name: copying kubeadm binary to host
      copy:
        src: /usr/bin/kubeadm
        dest: /usr/bin/kubeadm
        owner: root
        group: root
        mode: 0555
    - debug:
        msg: "{{ kubeadm_join_command }}"
    - name: running kubeadm join command
      command: "{{ kubeadm_join_command }}"
    - name: base kubeadm deploy
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/bin/kubeadm
