{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- $envAll := . }}

{{- $mounts_heat_trusts := .Values.pod.mounts.heat_trusts.heat_trusts }}
{{- $mounts_heat_trusts_init := .Values.pod.mounts.heat_trusts.init_container }}

{{- $serviceAccountName := "heat-trusts" }}
{{ tuple $envAll "trusts" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: heat-trusts
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "heat" "trusts" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.job.node_selector_key }}: {{ .Values.labels.job.node_selector_value }}
      initContainers:
{{ tuple $envAll "trusts" $mounts_heat_trusts_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: heat-trusts
          image: {{ $envAll.Values.images.tags.ks_service }}
          imagePullPolicy: {{ $envAll.Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.trusts | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          command:
            - bash
            - /tmp/trusts.sh
          volumeMounts:
            - name: heat-bin
              mountPath: /tmp/trusts.sh
              subPath: trusts.sh
              readOnly: true
{{ if $mounts_heat_trusts.volumeMounts }}{{ toYaml $mounts_heat_trusts.volumeMounts | indent 12 }}{{ end }}
          env:
{{- with $env := dict "ksUserSecret" $envAll.Values.secrets.identity.admin }}
{{- include "helm-toolkit.snippets.keystone_openrc_env_vars" $env | indent 12 }}
{{- end }}
            - name: SERVICE_OS_ROLES
              value: {{ .Values.conf.heat.DEFAULT.trusts_delegated_roles }}
            - name: SERVICE_OS_TRUSTEE
              value: {{ .Values.endpoints.identity.auth.heat_trustee.username }}
            - name: SERVICE_OS_TRUSTEE_DOMAIN
              value: {{ .Values.endpoints.identity.auth.heat_trustee.user_domain_name }}
      volumes:
        - name: heat-bin
          configMap:
            name: heat-bin
            defaultMode: 0555
{{ if $mounts_heat_trusts.volumes }}{{ toYaml $mounts_heat_trusts.volumes | indent 8 }}{{ end }}
