# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: centos | installing epel-release
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - epel-release

- name: centos | installing SElinux support packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - libselinux-python

- name: fedora | installing SElinux support packages
  when: ansible_distribution == 'Fedora'
  dnf:
    name: "{{item}}"
    state: installed
  with_items:
    - libselinux-python

- when: kubelet.pv_support_ceph
  name: installing ceph support packages
  include_role:
    name: deploy-package
    tasks_from: dist
  vars:
    packages:
      deb:
        - ceph-common
      rpm:
        - ceph-common

- when: kubelet.pv_support_nfs
  name: installing NFS support packages
  include_role:
    name: deploy-package
    tasks_from: dist
  vars:
    packages:
      deb:
        - nfs-common
      rpm:
        - nfs-utils

- name: installing LinuxBridge support
  when: kubelet.net_support_linuxbridge
  include_role:
    name: deploy-package
    tasks_from: dist
  vars:
    packages:
      deb:
        - bridge-utils
      rpm:
        - bridge-utils
