{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.deployment_datasource }}
{{- $envAll := . }}

{{- $serviceAccountName := "congress-datasource-dep" }}
{{ tuple $envAll "datasource" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: congress-datasource-dep
spec:
  replicas: {{ .Values.pod.replicas.datasource }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "congress" "datasource" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      affinity:
{{ tuple $envAll "congress" "datasource" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      initContainers:
{{ tuple $envAll "datasource" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.datasource.node_selector_key }}: {{ .Values.labels.datasource.node_selector_value }}
      containers:
      - name: congress-datasource
        image: {{ .Values.images.tags.congress_datasource }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        securityContext:
          runAsUser: {{ .Values.pod.user.congress.uid }}
        command:
          - /tmp/congress-datasource.sh
          - start
        volumeMounts:
          - name: etccongress
            mountPath: /etc/congress
          - name: congress-bin
            mountPath: /tmp/congress-datasource.sh
            subPath: congress-datasource.sh
            readOnly: true
          - name: congress-etc
            mountPath: /etc/congress/congress.conf
            subPath: congress.conf
            readOnly: true
          - name: congress-etc
            mountPath: /etc/congress/api-paste.ini
            subPath: api-paste.ini
            readOnly: true
          - name: congress-etc
            mountPath: /etc/congress/policy.json
            subPath: policy.json
            readOnly: true
      volumes:
        - name: etccongress
          emptyDir: {}
        - name: congress-bin
          configMap:
            name: congress-bin
            defaultMode: 0555
        - name: congress-etc
          configMap:
            name: congress-etc
            defaultMode: 0444

{{ end }}
